spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lovememoremyfirstcrush@gmail.com
    password: qwerty45215asdfgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000